import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "./toasts/Context-driven-toast/ToastProvider";
import ToastContainer from "./toasts/Context-driven-toast/ToastContainer";
import { ToastContainer as StoreToastContainer } from "@/app/toasts/Store-driven toast/ToastContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreToastContainer />
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
